name: website deployment
on: 
 push:
    branches: [ main ]
jobs:
        deploy:
                runs-on: ubuntu-latest
                steps:
                    - name: deploy website
                      uses: actions/checkout@v2
                    - name: deploy website to test.com
                      uses: appleboy/ssh-action@main
                      with:
                         host: ${{secrets.HOST}}
                         username: ${{secrets.USERNAME}}
                         key: ${{secrets.PRI_KEY}}

                         script:
                             /scripts/github.sh
                              echo 'Deployment successful to digital ocean'
