name: website deployment
on: [push]
jobs:
        deploy:
                runs-on: ubuntu-latest
                steps:
                    - uses: actions/checkout@master
                    - name: deploy website to test.com
                      uses: appleboy/scp-action@master
                      env:
                         HOST: ${{ secrets.HOST }}
                         USERNAME: ${{ secrets.USERNAME }}
                         PORT: ${{ secrets.PORT }}
                         KEY: ${{ secrets.KEY }}
                      with:
                          source: "/index.html"
                          target: "/var/www/test1.com/public_html"
                          strip_components: 1
