name: website deployment
on: [push]
jobs:
        deploy:
                runs-on: ubuntu-latest
                steps:
                    - name: deploy website
                      uses: actions/checkout@master 
                    - name: deploy website to test.com
                      uses: appleboy/ssh-action@master
                      with:
                         host: ${{secrets.HOST}}
                         username: ${{secrets.USERNAME}}
                         key: ${{secrets.pub_key}}

                         script:
                             /scripts/github.sh
                              echo 'Deployment successful to digital ocean'
