name: website deployment
on: [push]
jobs:
        deploy:
                runs-on: ubuntu-latest
                steps:
                    - uses: actions/checkout@master 
                    - name: deploy website to test.com
                      uses: appleboy/ssh-action@master
                      with:
                         HOST: ${{ secrets.HOST }}
                         USERNAME: ${{ secrets.USERNAME }}
                         KEY: ${{ secrets.PRI_KEY }}

                         script:
                             /scripts/github.sh
                              echo 'Deployment successful to digital ocean'
